/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) out_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};

/* F:(i0[5],i1[2])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54;
  a00=arg[0]? arg[0][0] : 0;
  a01=3.3333333333333335e-03;
  a02=arg[0]? arg[0][3] : 0;
  a03=arg[0]? arg[0][2] : 0;
  a04=5.0000000000000000e-01;
  a05=arg[0]? arg[0][4] : 0;
  a06=tan(a05);
  a06=(a04*a06);
  a06=atan(a06);
  a07=(a03+a06);
  a07=cos(a07);
  a07=(a02*a07);
  a07=(a01*a07);
  a08=2.;
  a09=arg[1]? arg[1][0] : 0;
  a10=(a01*a09);
  a11=(a01*a10);
  a11=(a11/a08);
  a11=(a02+a11);
  a12=7.9000000000000004e-01;
  a13=(a02/a12);
  a14=sin(a06);
  a13=(a13*a14);
  a13=(a01*a13);
  a14=(a01*a13);
  a14=(a14/a08);
  a14=(a03+a14);
  a15=arg[1]? arg[1][1] : 0;
  a16=(a01*a15);
  a17=(a01*a16);
  a17=(a17/a08);
  a17=(a05+a17);
  a17=tan(a17);
  a17=(a04*a17);
  a17=atan(a17);
  a18=(a14+a17);
  a18=cos(a18);
  a18=(a11*a18);
  a18=(a01*a18);
  a18=(a08*a18);
  a07=(a07+a18);
  a18=(a01*a09);
  a19=(a01*a18);
  a19=(a19/a08);
  a19=(a02+a19);
  a20=(a11/a12);
  a21=sin(a17);
  a20=(a20*a21);
  a20=(a01*a20);
  a21=(a01*a20);
  a21=(a21/a08);
  a21=(a03+a21);
  a22=(a01*a15);
  a23=(a01*a22);
  a23=(a23/a08);
  a23=(a05+a23);
  a23=tan(a23);
  a23=(a04*a23);
  a23=atan(a23);
  a24=(a21+a23);
  a24=cos(a24);
  a24=(a19*a24);
  a24=(a01*a24);
  a24=(a08*a24);
  a07=(a07+a24);
  a24=(a01*a09);
  a25=(a01*a24);
  a25=(a02+a25);
  a26=(a19/a12);
  a27=sin(a23);
  a26=(a26*a27);
  a26=(a01*a26);
  a27=(a01*a26);
  a27=(a03+a27);
  a28=(a01*a15);
  a29=(a01*a28);
  a29=(a05+a29);
  a29=tan(a29);
  a29=(a04*a29);
  a29=atan(a29);
  a30=(a27+a29);
  a30=cos(a30);
  a30=(a25*a30);
  a30=(a01*a30);
  a07=(a07+a30);
  a30=6.;
  a07=(a07/a30);
  a00=(a00+a07);
  a18=(a08*a18);
  a10=(a10+a18);
  a24=(a08*a24);
  a10=(a10+a24);
  a24=(a01*a09);
  a10=(a10+a24);
  a10=(a10/a30);
  a10=(a02+a10);
  a20=(a08*a20);
  a13=(a13+a20);
  a26=(a08*a26);
  a13=(a13+a26);
  a26=(a25/a12);
  a20=sin(a29);
  a26=(a26*a20);
  a26=(a01*a26);
  a13=(a13+a26);
  a13=(a13/a30);
  a13=(a03+a13);
  a22=(a08*a22);
  a16=(a16+a22);
  a28=(a08*a28);
  a16=(a16+a28);
  a28=(a01*a15);
  a16=(a16+a28);
  a16=(a16/a30);
  a05=(a05+a16);
  a16=tan(a05);
  a16=(a04*a16);
  a16=atan(a16);
  a28=(a13+a16);
  a28=cos(a28);
  a28=(a10*a28);
  a28=(a01*a28);
  a22=(a01*a09);
  a26=(a01*a22);
  a26=(a26/a08);
  a26=(a10+a26);
  a20=(a10/a12);
  a24=sin(a16);
  a20=(a20*a24);
  a20=(a01*a20);
  a24=(a01*a20);
  a24=(a24/a08);
  a24=(a13+a24);
  a18=(a01*a15);
  a07=(a01*a18);
  a07=(a07/a08);
  a07=(a05+a07);
  a07=tan(a07);
  a07=(a04*a07);
  a07=atan(a07);
  a31=(a24+a07);
  a31=cos(a31);
  a31=(a26*a31);
  a31=(a01*a31);
  a31=(a08*a31);
  a28=(a28+a31);
  a31=(a01*a09);
  a32=(a01*a31);
  a32=(a32/a08);
  a32=(a10+a32);
  a33=(a26/a12);
  a34=sin(a07);
  a33=(a33*a34);
  a33=(a01*a33);
  a34=(a01*a33);
  a34=(a34/a08);
  a34=(a13+a34);
  a35=(a01*a15);
  a36=(a01*a35);
  a36=(a36/a08);
  a36=(a05+a36);
  a36=tan(a36);
  a36=(a04*a36);
  a36=atan(a36);
  a37=(a34+a36);
  a37=cos(a37);
  a37=(a32*a37);
  a37=(a01*a37);
  a37=(a08*a37);
  a28=(a28+a37);
  a37=(a01*a09);
  a38=(a01*a37);
  a38=(a10+a38);
  a39=(a32/a12);
  a40=sin(a36);
  a39=(a39*a40);
  a39=(a01*a39);
  a40=(a01*a39);
  a40=(a13+a40);
  a41=(a01*a15);
  a42=(a01*a41);
  a42=(a05+a42);
  a42=tan(a42);
  a42=(a04*a42);
  a42=atan(a42);
  a43=(a40+a42);
  a43=cos(a43);
  a43=(a38*a43);
  a43=(a01*a43);
  a28=(a28+a43);
  a28=(a28/a30);
  a00=(a00+a28);
  a31=(a08*a31);
  a22=(a22+a31);
  a37=(a08*a37);
  a22=(a22+a37);
  a37=(a01*a09);
  a22=(a22+a37);
  a22=(a22/a30);
  a22=(a10+a22);
  a33=(a08*a33);
  a20=(a20+a33);
  a39=(a08*a39);
  a20=(a20+a39);
  a39=(a38/a12);
  a33=sin(a42);
  a39=(a39*a33);
  a39=(a01*a39);
  a20=(a20+a39);
  a20=(a20/a30);
  a20=(a13+a20);
  a35=(a08*a35);
  a18=(a18+a35);
  a41=(a08*a41);
  a18=(a18+a41);
  a41=(a01*a15);
  a18=(a18+a41);
  a18=(a18/a30);
  a05=(a05+a18);
  a18=tan(a05);
  a18=(a04*a18);
  a18=atan(a18);
  a41=(a20+a18);
  a41=cos(a41);
  a41=(a22*a41);
  a41=(a01*a41);
  a35=(a01*a09);
  a39=(a01*a35);
  a39=(a39/a08);
  a39=(a22+a39);
  a33=(a22/a12);
  a37=sin(a18);
  a33=(a33*a37);
  a33=(a01*a33);
  a37=(a01*a33);
  a37=(a37/a08);
  a37=(a20+a37);
  a31=(a01*a15);
  a28=(a01*a31);
  a28=(a28/a08);
  a28=(a05+a28);
  a28=tan(a28);
  a28=(a04*a28);
  a28=atan(a28);
  a43=(a37+a28);
  a43=cos(a43);
  a43=(a39*a43);
  a43=(a01*a43);
  a43=(a08*a43);
  a41=(a41+a43);
  a43=(a01*a09);
  a44=(a01*a43);
  a44=(a44/a08);
  a44=(a22+a44);
  a45=(a39/a12);
  a46=sin(a28);
  a45=(a45*a46);
  a45=(a01*a45);
  a46=(a01*a45);
  a46=(a46/a08);
  a46=(a20+a46);
  a47=(a01*a15);
  a48=(a01*a47);
  a48=(a48/a08);
  a48=(a05+a48);
  a48=tan(a48);
  a48=(a04*a48);
  a48=atan(a48);
  a49=(a46+a48);
  a49=cos(a49);
  a49=(a44*a49);
  a49=(a01*a49);
  a49=(a08*a49);
  a41=(a41+a49);
  a49=(a01*a09);
  a50=(a01*a49);
  a50=(a22+a50);
  a51=(a44/a12);
  a52=sin(a48);
  a51=(a51*a52);
  a51=(a01*a51);
  a52=(a01*a51);
  a52=(a20+a52);
  a53=(a01*a15);
  a54=(a01*a53);
  a54=(a05+a54);
  a54=tan(a54);
  a04=(a04*a54);
  a04=atan(a04);
  a54=(a52+a04);
  a54=cos(a54);
  a54=(a50*a54);
  a54=(a01*a54);
  a41=(a41+a54);
  a41=(a41/a30);
  a00=(a00+a41);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a03=(a03+a06);
  a03=sin(a03);
  a02=(a02*a03);
  a02=(a01*a02);
  a14=(a14+a17);
  a14=sin(a14);
  a11=(a11*a14);
  a11=(a01*a11);
  a11=(a08*a11);
  a02=(a02+a11);
  a21=(a21+a23);
  a21=sin(a21);
  a19=(a19*a21);
  a19=(a01*a19);
  a19=(a08*a19);
  a02=(a02+a19);
  a27=(a27+a29);
  a27=sin(a27);
  a25=(a25*a27);
  a25=(a01*a25);
  a02=(a02+a25);
  a02=(a02/a30);
  a00=(a00+a02);
  a13=(a13+a16);
  a13=sin(a13);
  a10=(a10*a13);
  a10=(a01*a10);
  a24=(a24+a07);
  a24=sin(a24);
  a26=(a26*a24);
  a26=(a01*a26);
  a26=(a08*a26);
  a10=(a10+a26);
  a34=(a34+a36);
  a34=sin(a34);
  a32=(a32*a34);
  a32=(a01*a32);
  a32=(a08*a32);
  a10=(a10+a32);
  a40=(a40+a42);
  a40=sin(a40);
  a38=(a38*a40);
  a38=(a01*a38);
  a10=(a10+a38);
  a10=(a10/a30);
  a00=(a00+a10);
  a18=(a20+a18);
  a18=sin(a18);
  a18=(a22*a18);
  a18=(a01*a18);
  a37=(a37+a28);
  a37=sin(a37);
  a39=(a39*a37);
  a39=(a01*a39);
  a39=(a08*a39);
  a18=(a18+a39);
  a46=(a46+a48);
  a46=sin(a46);
  a44=(a44*a46);
  a44=(a01*a44);
  a44=(a08*a44);
  a18=(a18+a44);
  a52=(a52+a04);
  a52=sin(a52);
  a52=(a50*a52);
  a52=(a01*a52);
  a18=(a18+a52);
  a18=(a18/a30);
  a00=(a00+a18);
  if (res[0]!=0) res[0][1]=a00;
  a45=(a08*a45);
  a33=(a33+a45);
  a51=(a08*a51);
  a33=(a33+a51);
  a50=(a50/a12);
  a04=sin(a04);
  a50=(a50*a04);
  a50=(a01*a50);
  a33=(a33+a50);
  a33=(a33/a30);
  a20=(a20+a33);
  if (res[0]!=0) res[0][2]=a20;
  a43=(a08*a43);
  a35=(a35+a43);
  a49=(a08*a49);
  a35=(a35+a49);
  a09=(a01*a09);
  a35=(a35+a09);
  a35=(a35/a30);
  a22=(a22+a35);
  if (res[0]!=0) res[0][3]=a22;
  a47=(a08*a47);
  a31=(a31+a47);
  a08=(a08*a53);
  a31=(a31+a08);
  a01=(a01*a15);
  a31=(a31+a01);
  a31=(a31/a30);
  a05=(a05+a31);
  if (res[0]!=0) res[0][4]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
